fedora:
    image: fedora:26
    when: always
    script:
        # - dnf upgrade --refresh -y
        - dnf install --refresh -y @development-tools fedora-packager rpmdevtools
        - dnf install -y swig python-devel openssl-devel openssl python-setuptools python-twisted
        - python setup.py build test

centos6:
    image: centos:6
    when: always
    script:
        - yum upgrade -y
        - yum groupinstall -y "Development tools"
        - yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
        - yum install -y python-devel openssl-devel openssl python-setuptools python-twisted python-unittest2
        - python setup.py build test

python27:
    image: python:2.7
    when: always
    script:
        - apt-get update -q -y
        - apt-get install -y swig libssl-dev libssl1.0.0 python-dev openssl python-twisted python-setuptools
        - python setup.py clean build test

python34:
    image: python:3.4
    when: always
    allow_failure: yes
    script:
        - apt-get update -q -y
        - apt-get install -y swig libssl-dev libssl1.0.0 python3-dev openssl python3-setuptools
        - easy_install3 Twisted
        - python3 setup.py clean build test

python36:
    image: python:3.6
    when: always
    allow_failure: yes
    script:
        - apt-get update -q -y
        - apt-get install -y swig libssl-dev libssl1.0.0 python3-dev openssl python3-setuptools
        - easy_install3 Twisted
        - python3 setup.py clean build test
